# yaml-language-server: $schema=https://raw.githubusercontent.com/RedHatInsights/frontend-components/refs/heads/master/packages/config-utils/src/feo/spec/frontend-crd.schema.json
apiVersion: v1
kind: Template
metadata:
  name: astro-virtual-assistant-frontend
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: virtual-assistant
    spec:
      feoConfigEnabled: true
      envName: ${ENV_NAME}
      title: Virtual assistant
      deploymentRepo: https://github.com/RedHatInsights/astro-virtual-assistant-frontend
      API:
        versions:
          - v1
        specs:
          - url: https://console.redhat.com/api/astro-virtual-assistant-v2/v2/openapi.json
            bundleLabels: ["insights"]
      frontend:
        paths:
          - /apps/virtual-assistant
      image: ${IMAGE}:${IMAGE_TAG}
      pushCacheEnabled: true
      module:
        manifestLocation: "/apps/virtual-assistant/fed-mods.json"
        modules:
          - id: "virtual-assistant"
            module: "./RootApp"
            routes: 
            - pathname: "/staging/virtual-assistant"

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/virtual-assistant-frontend
